### ISSUE TITLE
RPM package for Generic Linux should provide "jre-17" capability to match OpenJDK packages

### ISSUE THREAD

**Issue by andrewjroth** [corretto/corretto-17#102]
### Describe the bug
The RPM Package (generic Linux) is not configured to provide "jre-17".  As a result, packages that require this will not install as they are missing a dependency.  If available, a different JRE will be installed automatically from a configured OS repository over Corretto.

### To Reproduce

1. Download and install the Amazon Corretto RPM on an OS other than Amazon Linux 2, such as CentOS 7 or Rocky 8.
2. Identify an RPM package that requires "jre-17" and attempt to install it using `rpm` or `yum`.  For me, this is [Neo4j Server](https://neo4j.com/docs/operations-manual/5/installation/linux/rpm/), but other packages might exist with this dependancy.
3. Install will either fail with a dependency issue or another java-17 (such as `java-17-openjdk`) will be installed as a dependency.

### Expected behavior
RPM package installs normally, without issue.

### Screenshots
```
$ sudo rpm -i cypher-shell.rpm neo4j.rpm
error: Failed dependencies:
	jre-17 >= 17 is needed by cypher-shell-5.1.0-1.noarch
	jre-17 is needed by neo4j-5.1.0-1.noarch
```

### Platform information
    OS: CentOS 7, Rocky 8
    Version:  Corretto-17.0.5.8.1 (build 17.0.5+8-LTS)

```shell
$ java --version
openjdk 17.0.5 2022-10-18 LTS
OpenJDK Runtime Environment Corretto-17.0.5.8.1 (build 17.0.5+8-LTS)
OpenJDK 64-Bit Server VM Corretto-17.0.5.8.1 (build 17.0.5+8-LTS, mixed mode, sharing)
```

### Additional context
I'm aware that there exists an RPM option to disable dependency checks (`--nodeps`).  This is a workaround, but the package should be updated to include the correct "provides" capabilities to match the official OpenJDK package.

From Rocky 8:
```shell
$ rpm -q --provides java-17-openjdk
java-17 = 1:17.0.5.0.8-2.el8_6
java-17-openjdk = 1:17.0.5.0.8-2.el8_6
java-17-openjdk(x86-64) = 1:17.0.5.0.8-2.el8_6
jre-17 = 1:17.0.5.0.8-2.el8_6
jre-17-openjdk = 1:17.0.5.0.8-2.el8_6
```

Amazon Corretto RPM package should include these for optimal compatability.

**Comment by alvdavi** [comment]
Hi,

Thank you for reporting this. We are going through the RPMs of our Generic Linux distribution to better configure the list of provides.

**Comment by andrewjroth** [comment]
Thank you!  Do you have any ETA on when the RPM will be updated or will this issue stay open until it's updated?

**Comment by lutkerd** [comment]
Latest RPMs have the requested provides.

```
rpm -qp java-17-amazon-corretto-devel-17.0.8.7-1.x86_64.rpm  --provides
java-17-amazon-corretto-devel = 1:17.0.8.7-1
java-17-devel = 1:17.0.8.7
java-17-openjdk-devel = 1:17.0.8.7-1
java-sdk-17 = 1:17.0.8.7
java-sdk-17-openjdk  = 1:17.0.8.7-1
java-17 = 1:17.0.8.7
java-17-openjdk = 1:17.0.8.7
jre = 1:17.0.8.7
jre-17 = 1:17.0.8.7
jre-17-openjdk = 1:17.0.8.7
```
