### ISSUE TITLE
A fatal error has been detected by the Java Runtime Environment: EXCEPTION_ACCESS_VIOLATION (0xc0000005)

### ISSUE THREAD

**Issue by Tharrington86** [corretto/corretto-17#105]
### Describe the bug
I am working on a desktop application that uses serial communication to retrieve debug data from a device using an Edgeport/1i. When I actuate the button to navigate to a particular feature, the app closes and a log file is generated if, and only if, the Edgeport is plugged into my PC.

### To Reproduce
Click on the feature button

### Expected behavior
The feature launches and data acquisition should begin.

### Platform information
    OS: Windows 11
    Version "Corretto-17.0.5"

[hs_err_pid2388.log](https://github.com/corretto/corretto-17/files/10240110/hs_err_pid2388.log)

**Comment by lutkerd** [comment]
This appears to be a crash in the native code provided by jSerialComm, it appears you are running v2.9.2 and v2.9.3 was released last month. Please see if the latest jSerialComm fixes your issue and [file a bug](https://github.com/Fazecast/jSerialComm/issues) with them if you are still having issues.

```
Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
j  com.fazecast.jSerialComm.SerialPort.getCommPortsNative()[Lcom/fazecast/jSerialComm/SerialPort;+0 com.fazecast.jSerialComm
j  com.fazecast.jSerialComm.SerialPort.getCommPorts()[Lcom/fazecast/jSerialComm/SerialPort;+0 com.fazecast.jSerialComm
j  com.americantraction.connection.serial.SerialConnection.getFirstOpenPort()Lcom/fazecast/jSerialComm/SerialPort;+0 STAG
j  com.americantraction.connection.serial.SerialConnection.<init>()V+6 STAG
j  com.americantraction.gui.LineChartController.initialize()V+56 STAG
v  ~StubRoutines::call_stub

```

**Comment by Tharrington86** [comment]
Thank you for the reply. I followed you recommendation and the issue remains even after updating to the latest version. I will submit an issue with jSerialComm. If you have anymore insight, I would appreciate it.

**Comment by lutkerd** [comment]
There isn't more info we can easily get from the hs_err without symbols for the native code. It just shows we are in native code somewhere from the `getCommPortsNative` call.

```
Stack: [0x000000c4da900000,0x000000c4daa00000],  sp=0x000000c4da9fbca8,  free space=1007k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  0x00007ffa170f6697

Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
j  com.fazecast.jSerialComm.SerialPort.getCommPortsNative()[Lcom/fazecast/jSerialComm/SerialPort;+0 com.fazecast.jSerialComm
```

**Comment by Tharrington86** [comment]
I just wanted to update before closing this issue. I incrementally decremented versions of this library until I found that v2.7.0 and previous do not cause the JVM to crash. I have since been in contact with the developer of JSerialComm to troubleshoot what introduced this failure.
