### ISSUE TITLE
Regression related to JDK-8246094: [macos] Sound Recording and playback is not working

### ISSUE THREAD

**Issue by benty-amzn** [corretto/corretto-17#11]
Due to a bug in the signing and notarization process for Corretto, the updated entitlements from [JDK-8246094](https://bugs.openjdk.java.net/browse/JDK-8246094) are not being applied properly. This results in Corretto for macos being unable to prompt the user for access to the microphone, and prevents users from recording sound.

While we address this issue, Corretto 17 for macos will remain in EA / preview.
Once this issue is resolved, we will release Corretto 17 for macos as GA.

**Comment by wkbrd** [comment]
Hi @benty-amzn , is this also blocking Corretto 17 from releasing as GA for Linux and Windows?  If not, any idea when it will release for those platforms?

**Comment by davecurrie** [comment]
You can consider the existing Windows and Linux binaries GA, we will be announcing shortly.

**Comment by benty-amzn** [comment]
This issue has been resolved and Corretto 17 is now GA, version [17.0.0.35.1](https://github.com/corretto/corretto-17/releases/tag/17.0.0.35.1) for all platforms except macos, and [17.0.0.35.2](https://github.com/corretto/corretto-17/releases/tag/17.0.0.35.2) for macos.
