### ISSUE TITLE
Corretto for BSD

### ISSUE THREAD

**Issue by sagsaw** [corretto/corretto-17#111]
Is it possible to have Corretto for BSD operating system?

I am shifting from Linux to using BSD as server operating system and would require Coretto.

FreeBSD already has OpenJDK ported to it.

When will Corretto be available for BSD operating systems or specifically FreeBSD and OpenBSD?

**Comment by earthling-amzn** [comment]
Hi. Thank you for your inquiry. We have no plans at this time to release builds for BSD, but the corretto sources _should_ build on that platform.
