### ISSUE TITLE
Minecraft 1.19.4 with java-17 crashes way too much.

### ISSUE THREAD

**Issue by ghost** [corretto/corretto-17#126]
Hello, 
I've been running the Minecraft Server since 2019 with absolutely no issues. However since I updated to java 17 I only ran into issues, sometimes even losing hours of progress with corrupted chunks. Minecraft was always my favorite game, but with all those crashes I can't take it anymore. How do other servers run 24/7 with no issues? I'm not sure if this is my OS, maybe? Or if its a missing dependency or just something else. I have very little knowledge in Java and I really need help.

I started PaperSpigot 1.19.4 and It may run for few hours and crash then, or It crashes just in a few seconds.

I was expecting to run it in a Linux-screen with no Issues, (I did this back in 1.18) and I had no issues, yes Corretto reduces the crashed a lot, but I would like to have a crash-free experience, like I did before. If there's no solution, then my last option would be to move back to Windows, or virtualiter it differently. I also have a crash file "_usr_lib_jvm_java-17-amazon-corretto_bin_java.1000.crash" but its 334 MB big I could give you that too, but GitHub has a limit of 25 MB at least here. If possible, I would like to stay on Ubuntu, because going back to Windows would be the very last option that I would need to take.

Take a look at all the logs that I provided, and if you need more information I can surely hand out. Any help would be really appreciated. :)

regards Conrad

### Platform information
 My OS is: Ubuntu 22.04.06 LTS 64 bit

### Java information
openjdk version "17.0.7" 2023-04-18 LTS
OpenJDK Runtime Environment Corretto-17.0.7.7.1 (build 17.0.7+7-LTS)
OpenJDK 64-Bit Server VM Corretto-17.0.7.7.1 (build 17.0.7+7-LTS, mixed mode, sharing

[replay_pid368908.log](https://github.com/corretto/corretto-17/files/11439640/replay_pid368908.log)
[hs_err_pid368908.log](https://github.com/corretto/corretto-17/files/11439642/hs_err_pid368908.log)

**Comment by lutkerd** [comment]
Hi,
Thanks for reporting this. Would you be able to reproduce this using a fastdebug build of Corretto17? It may provide more context or have a clear assertion on why this is occuring. You can download the build from [here](https://downloads.corretto.aws/#/downloads?build=nightly&version=17&platform=generic_linux&debugLevel=fastdebug&architecture=x64&branch=develop).

Thanks.

**Comment by navyxliu** [comment]
hi, @n4n0x-devs 
your crash report [hs_err_pid368908.log](https://github.com/corretto/corretto-17/files/11439642/hs_err_pid368908.log) suggests that JVM crashed in C1 compiler thread. It had compiled the method but failed to installed it to codecache. codecache is a managed memory area for generated code. 

The stacktrace looks like this:
```
Stack: [0x00007f2d0fcfd000,0x00007f2d0fdfe000],  sp=0x00007f2d0fdfc1e0,  free space=1020k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
V  [libjvm.so+0x7ec258]  CodeHeap::allocate(unsigned long)+0x78
V  [libjvm.so+0x5b6bd9]  CodeCache::allocate(int, int, bool, int)+0xa9
```

Have you collected other crash reports? Are they all due to this issue?

**Comment by ghost** [comment]
> hi, @n4n0x-devs your crash report [hs_err_pid368908.log](https://github.com/corretto/corretto-17/files/11439642/hs_err_pid368908.log) suggests that JVM crashed in C1 compiler thread. It had compiled the method but failed to installed it to codecache. codecache is a managed memory area for generated code.
> 
> The stacktrace looks like this:
> 
> ```
> Stack: [0x00007f2d0fcfd000,0x00007f2d0fdfe000],  sp=0x00007f2d0fdfc1e0,  free space=1020k
> Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
> V  [libjvm.so+0x7ec258]  CodeHeap::allocate(unsigned long)+0x78
> V  [libjvm.so+0x5b6bd9]  CodeCache::allocate(int, int, bool, int)+0xa9
> ```
> 
> Have you collected other crash reports? Are they all due to this issue?

I'm not sure if this is cause by "codecache" or whatever, maybe it's the "ramdrive" that I'm using. I'm using a 32 GB ramdrive to cache temporary content, I will disable the ramdrive and try to run java-17 and see if this issue still occurs.

**Comment by ghost** [comment]
> Hi, Thanks for reporting this. Would you be able to reproduce this using a fastdebug build of Corretto17? It may provide more context or have a clear assertion on why this is occuring. You can download the build from [here](https://downloads.corretto.aws/#/downloads?build=nightly&version=17&platform=generic_linux&debugLevel=fastdebug&architecture=x64&branch=develop).
> 
> Thanks.

Hi, I downloaded that custom version of java-17, that you provided, but its insanely slow, and the performance is near unplayable. I have like 72 plugins and it takes around 7 to 8 seconds to boot the minecraft server, now however its takes over 110 seconds, yeah I don't know if I'm doing the correct thing here with the "fastdebug" thingy. Yeah it still crashes, maybe because its so insanely slow, I will provide the logs.

[hs_err_pid127236.log](https://github.com/corretto/corretto-17/files/11454068/hs_err_pid127236.log)
[mc-1.19.4.log](https://github.com/corretto/corretto-17/files/11454069/mc-1.19.4.log)

**Comment by lutkerd** [comment]
The fastdebug build is strictly to see if we can get more information from the crash and it is expected to be a slower than a production build.  Are there more hs_err logs either from the fastdebug or production build? The new hs_err is showing a different crash than the original log.

**Comment by ghost** [comment]
> The fastdebug build is strictly to see if we can get more information from the crash and it is expected to be a slower than a production build. Are there more hs_err logs either from the fastdebug or production build? The new hs_err is showing a different crash than the original log.

Surely I can provide more logs, here they are :)

[hs_err_pid71165.log](https://github.com/corretto/corretto-17/files/11454312/hs_err_pid71165.log)
[hs_err_pid8418.log](https://github.com/corretto/corretto-17/files/11454313/hs_err_pid8418.log)
[hs_err_pid9599.log](https://github.com/corretto/corretto-17/files/11454314/hs_err_pid9599.log)
[replay_pid18642.log](https://github.com/corretto/corretto-17/files/11454316/replay_pid18642.log)
[replay_pid368908.log](https://github.com/corretto/corretto-17/files/11454317/replay_pid368908.log)
[replay_pid8418.log](https://github.com/corretto/corretto-17/files/11454318/replay_pid8418.log)
[crash-2023-05-10_02.29.54-server.txt](https://github.com/corretto/corretto-17/files/11454320/crash-2023-05-10_02.29.54-server.txt)
[crash-2023-05-10_06.37.33-server.txt](https://github.com/corretto/corretto-17/files/11454321/crash-2023-05-10_06.37.33-server.txt)
[hs_err_pid18642.log](https://github.com/corretto/corretto-17/files/11454322/hs_err_pid18642.log)
[hs_err_pid368908.log](https://github.com/corretto/corretto-17/files/11454323/hs_err_pid368908.log)
[hs_err_pid53122.log](https://github.com/corretto/corretto-17/files/11454324/hs_err_pid53122.log)

**Comment by navyxliu** [comment]
hi, @n4n0x-devs 
Thanks for providing us extra crash reports. 

We found that your java program failed in a variety of places. Some are in GC thread. Some are in the Register Allocation of C2 Compiler Thread. Some are in other hotspot Runtime.  

It's very unlikely there are so many severe bugs in JVM. It passed huge amount of tests before releasing. I would inspect lower-level systems first. 

1. first of all, are you running the program in a container environment?  how about you run it directly? 
2. Could you migrate your program to another Linux host and see if those errors still occur? if the problem goes away, I would run hardware diagnostic on your host.

**Comment by ghost** [comment]
> hi, @n4n0x-devs Thanks for providing us extra crash reports.
> 
> We found that your java program failed in a variety of places. Some are in GC thread. Some are in the Register Allocation of C2 Compiler Thread. Some are in other hotspot Runtime.
> 
> It's very unlikely there are so many severe bugs in JVM. It passed huge amount of tests before releasing. I would inspect lower-level systems first.
> 
> 1. first of all, are you running the program in a container environment?  how about you run it directly?
> 2. Could you migrate your program to another Linux host and see if those errors still occur? if the problem goes away, I would run hardware diagnostic on your host.


1. No, I run it directly on a dedicated Server at home, no Docker involved.
2. I can try but first of all I will disable my ramdrive maybe those errors go away. I will try to delete cache, reboot and see if it still crashes.

**Comment by lutkerd** [comment]
There are also some native libraries getting loaded that could be causing problems as well. I don't know if these are part of the PaperSpigot server or some of the plugins you are loading. It may be worth it to disable some or all of the plugins and see if that improves stability.

```
Event: 0,540 Loaded shared library /tmp/jansi-2.4.0-ca0ee501bc1f3e62-libjansi.so
Event: 0,675 Loaded shared library /mnt/ramdrive/cache/JNA/temp/jna13251696149914573723.tmp
Event: 3,353 Loaded shared library /tmp/native-16587099268636518087.so
Event: 3,354 Loading shared library /tmp/native-9483920104704361517.so failed, libcrypto.so.3: Kann die Shared-Object-Datei nicht öffnen: Datei oder Verzeichnis nicht gefunden
Event: 3,354 Loaded shared library /tmp/native-6260175416005782189.so
Event: 9,463 Loaded shared library /tmp/sqlite-3.41.0.0-cd2587ec-dec3-4b3e-99eb-971f1240c010-libsqlitejdbc.so
```

**Comment by ghost** [comment]
> There are also some native libraries getting loaded that could be causing problems as well. I don't know if these are part of the PaperSpigot server or some of the plugins you are loading. It may be worth it to disable some or all of the plugins and see if that improves stability.
> 
> ```
> Event: 0,540 Loaded shared library /tmp/jansi-2.4.0-ca0ee501bc1f3e62-libjansi.so
> Event: 0,675 Loaded shared library /mnt/ramdrive/cache/JNA/temp/jna13251696149914573723.tmp
> Event: 3,353 Loaded shared library /tmp/native-16587099268636518087.so
> Event: 3,354 Loading shared library /tmp/native-9483920104704361517.so failed, libcrypto.so.3: Kann die Shared-Object-Datei nicht öffnen: Datei oder Verzeichnis nicht gefunden
> Event: 3,354 Loaded shared library /tmp/native-6260175416005782189.so
> Event: 9,463 Loaded shared library /tmp/sqlite-3.41.0.0-cd2587ec-dec3-4b3e-99eb-971f1240c010-libsqlitejdbc.so
> ```


Ah, I think it may be the ramdrives fault. Usually I don't have any problems, but maybe I can't it at least for PaperSpigot :)

The /tmp directory is also a a ramdrive, maybe this is causing those crashes? What if I disable the /tmp ramdrive? Will then my temporary files be stored on the local disk? I guess so.

***/etc/fstab***

```
tmpfs           /tmp            tmpfs   rw,nosuid,nodev,size=2048m   0  0
```

I really don't understand (if) why the ramdrive is causing such issues, is the latency too high? Or are missing permissions, I have really no clue. I'm gonna be offtopic for a bit, I've been using ramdrives for about half a year now and I never run into any issues, besides in java. I wanna convert a long 3 hour video into thousands of fragments? Sure why not, let's use the ramdrive and then put it into a .zip or .tar archive. I will try different methods starting java.

**Comment by lutkerd** [comment]
I doubt the ramdrive is the issue, that would be more around I/O latency. You can use standard Linux tools to see if the server does a lot of I/O, the ramdrive could just be total overkill for your use case. When we see crashes on a single machine in a wide variety of locations, that is sometimes an indication of bad RAM or another hardware issue, or from a bug in other native code causing memory corruption.

**Comment by ghost** [comment]
> I doubt the ramdrive is the issue, that would be more around I/O latency. You can use standard Linux tools to see if the server does a lot of I/O, the ramdrive could just be total overkill for your use case. When we see crashes on a single machine in a wide variety of locations, that is sometimes an indication of bad RAM or another hardware issue, or from a bug in other native code causing memory corruption.

Hm... then if its not the ramdrive what is it then? Something is clearly wrong. I can't downgrade to java-16 because its not supported by modern Minecraft versions. If those crashes still occur (which they sadly do), then I really have to use Windows :( Or maybe I will use something like Parallel-Desktops for Ubuntu just to run java. lol I really don't know whats causing all this. I tried wine(bottler) a Windows App Emulator for Linux but its super slow and crashes too due to Memory overflow, or whatever was that crash message. I would love to have it as a few Months ago, without any crashes whatever. If there's no way to fix this, then I really have to migrate to Windows, which I really don't want to. Maybe the java start arguments are bad? Maybe I allocated too much RAM to java, what do you guys think? those ***-Xms & -Xmx*** arguments say the game how much memory it can use at max. If you have a java-17 minecraft server, tell me if you can the start comment mine looks something like this (bash)

```
#!/bin/bash

java_8="/usr/lib/jvm/java-8-openjdk-amd64/bin/java"
java_17="/usr/lib/jvm/java-17-amazon-corretto/bin/java"
java_17_debug="/usr/lib/jvm/amazon-corretto-17.0.8.2.1-linux-x64-fastdebug/bin/java"
java_19="/usr/lib/jvm/java-19-amazon-corretto/bin/java"
paper="/home/conrad/PaperSpigot 1.19.4/paper-1.19.4-527.jar"
purpur="/home/conrad/PaperSpigot 1.19.4/purpur-1.19.4-1968.jar"


export NEWT_COLORS='
window=blue
border=green
textbox=white,green
button=green
'

while [ 1 ]
do
CHOICE=$(
whiptail --title "Minecraft Menü" --menu "Was möchtest du tun?" 19 120 11 \
    "1)" "Minecraft Ordner anzeigen." \
    "2)" "Minecraft Proxy starten." \
    "3)" "Minecraft 1.19.4 logs." \
    "4)" "Minecraft beta 1.7.2[s] starten." \
    "5)" "Minecraft 1.19.4[s] starten." \
    "6)" "Minecraft 1.19.4 starten." \
    "7)" "Minecraft beta 1.7.2 Backup erstellen." \
    "8)" "Minecraft 1.19.4 Backup erstellen." \
    "9)" "zu Minecraft beta 1.7.2 wechseln" \
    "10)" "zu Minecraft 1.19.4 wechseln" \
    "❌)" "Menü verlassen." 3>&2 2>&1 1>&3
)

result=$(exit)
case $CHOICE in
    "1)")
        ( cd /mnt/giga/Minecraft ; ls -alh --color=auto )
    break;;
    "2)")
        ( whiptail --title "Fehler 404" --msgbox "404, Proxy wurde nicht gefunden." 8 78 ; echo "404, Proxy wurde nicht gefunden." ) # cd '/home/conrad/MCProxy' ; screen -S MC-Proxy /usr/lib/jvm/jre1.8.0_333/bin/java -Xms1G -Xmx8G -jar BungeeCord.jar nogui
    break;;
    "3)")
        ( tail '/home/conrad/PaperSpigot 1.19.4/mc-1.19.4.log' ; echo "" )
    break;;    
    "4)")
        ( cd '/home/conrad/Bukkit Beta 1.7.2' ; screen -L -Logfile mc-beta-1.7.2.log -A -S Minecraft-beta-1.7.2 -d -m "${java_8}" -Xms8G -Xmx16G -jar craftbukkit.jar nogui && whiptail --title "INFO" --msgbox "Minecraft beta 1.7.2 läuft im hintergrund." 8 78 && screen -ls | grep --color=auto "Minecraft-beta-1.7.2" )
    break;;
    "5)")
        ( cd '/home/conrad/PaperSpigot 1.19.4' ; screen -L -Logfile mc-1.19.4.log -A -S Minecraft-1.19.4 -d -m "${java_17}" -Xms24G -Xmx32G -jar "${purpur}" nogui && whiptail --title "INFO" --msgbox "Minecraft 1.19.4 läuft im hintergrund." 8 78 && screen -ls | grep --color=auto "Minecraft-1.19.4" ) # -Xmn16G -XX:ParallelGCThreads=8 -XX:MaxGCPauseMillis=2000 -XX:+DisableExplicitGC
    break;;
    "6)")
        ( cd '/home/conrad/PaperSpigot 1.19.4' ; "${java_17}" -Xms24G -Xmx32G -jar "${paper}" -nogui )
    break;;
    "7)")
        ( cd /home/conrad ; sudo tar -cpvf "/mnt/giga/backups/backup von Bukkit Beta 1.7.2 am $(date '+%d.%m.%Y um %H：%M') Uhr.tar" "Bukkit Beta 1.7.2" && whiptail --title "INFO" --msgbox "Backup von Minecraft beta 1.7.2 wurde erfolgreich erstellt." 8 78 ) # sudo tar -cpvf - "/home/conrad/Bukkit Beta 1.7.2" > "/mnt/giga/backups/backup von Bukkit Beta 1.7.2 am $(date '+%d.%m.%Y um %H：%M') Uhr.tar"
    break;;
    "8)")
        ( cd /home/conrad ; sudo tar -cpvf "/mnt/giga/backups/backup von PaperSpigot 1.19.4 am $(date '+%d.%m.%Y um %H：%M') Uhr.tar" "PaperSpigot 1.19.4" && whiptail --title "INFO" --msgbox "Backup von Minecraft 1.19.4 wurde erfolgreich erstellt." 8 78 ) # sudo zip -r -0 "/mnt/giga/backups/backup von PaperSpigot 1.19.4 am $(date '+%d.%m.%Y um %H：%M') Uhr.zip" "/home/conrad/PaperSpigot 1.19.4"
    break;;
    "9)")
        ( screen -r Minecraft-beta-1.7.2 )
    break;;
    "10)")
        ( screen -r Minecraft-1.19.4 )
    break;;
    "❌)")
    exit;;

esac
whiptail --msgbox "$result" 20 78
done
exit
```
Take a look at the bash script, especially at those java start arguments. The ***[s]*** stands for ***screen***

**Comment by ghost** [comment]
I have a backup of openjdk-17, which I used with no issues, mostly ;) Last update was at 10th August 2022.


```
cd /mnt/giga/backups ; sudo tar -xvf ⧸usr⧸lib⧸jvm⧸jdk-17.tar -C /usr/lib/jvm/
```


I'm not sure if this will do the trick, I'm pretty sure it will crash again, but at least for now it seems to work, at least for now :D
I will let java-17 run for a few hours (hopefully) and see if its working or not.

My CPU's overall temperature is 30 - 32 °C ; 86 - 89.6 °F, the water cooling unit for my CPU has 2 fans, but the 2nd cooling fan is spinning slowly, due to some cable issues, but I hope that's not the case for crashing java.

**Comment by lutkerd** [comment]
Too much heap space `-Xms -Xmx` is not the issue, as I said it is very likely either hardware issue, like a faulty memory module, or something in 1 of the plugins via those native libraries that get loaded. The easiest thing to try would be to identify the plugings with native code (.so files) and stop running them to see if the crashes continue.

I don't think using an an older version of Java is a good long term solution either as there will be missing security patches and you will eventually have to update anyway.

**Comment by ghost** [comment]
> Too much heap space `-Xms -Xmx` is not the issue, as I said it is very likely either hardware issue, like a faulty memory module, or something in 1 of the plugins via those native libraries that get loaded. The easiest thing to try would be to identify the plugings with native code (.so files) and stop running them to see if the crashes continue.
> 
> I don't think using an an older version of Java is a good long term solution either as there will be missing security patches and you will eventually have to update anyway.

Shall I send you the plugins that I'm using? The plugins folder is around 54.3 MB big.

**Comment by lutkerd** [comment]
Try running with no plugins first. You may also want to run some kind of memory testing tool to rule out hardware issues.

**Comment by ghost** [comment]
> Try running with no plugins first. You may also want to run some kind of memory testing tool to rule out hardware issues.

I did it a few times already without plugins, crashes too but...

I disabled, removed and unmounted all ramdrives and symbolic links and I see no crashes. I copied the entire Minecraft Server from Ubuntu to Windows 10 and on Windows they're no crashed either, which is good. Maybe Minecraft doesn't like symbolic links, like I don't really like to keep cache or logs so I mount a ramdrive, link all to the ramdrive and then when I reboot all the cache and logs are gone, but yeah at least for Minecraft that doesn't work too well, cuz it crashes all the time because of it. My last assumption would be something wrong in Ubuntu 20.04, but I will play a bit, teleport around and see if it crashes again.

Is this bad?
```
[13:09:51 ERROR]: BlockEntity threw exception at PistonHouse_nether:149,54,-109
```
or this

```
[13:25:00 ERROR]: [NewChunkHolder] Failed to save chunk data (-67392,-67569) in world '2b2t'
```
?

I mean sure, errors are always bad, but not saving a chunk doesn't mean its corrupted, it's just that the "progress" is gone.

I sadly can not replicate this situation, but one time a few weeks ago the Minecraft server crashed because of a ***Parrot***, yes a Parrot, sometimes I think Minecraft is a troll game, with included crashes. Alright I will let Minecraft run a few hours in the background and see if it still crashes.

**Comment by ghost** [comment]
> Try running with no plugins first. You may also want to run some kind of memory testing tool to rule out hardware issues.

Can you provide me a **memory testing tool**? I would love to see the erros in detail, I will check the ramsticks, maybe they are in the wrong slots.

**Comment by lutkerd** [comment]
I can't recommend one, but you can search for one or check the PaperSpigot issues forum for their recommendations.

**Comment by ghost** [comment]
> I can't recommend one, but you can search for one or check the PaperSpigot issues forum for their recommendations.

I think I may found the problem, its the **libjvm.so** module idk how to call this. But I think this is the faulty part. I tried to reinstall with apt or nala but didn't really fix the problem I will provide my libjvm.so, so you can take a look at it.

```
drwxr-xr-x 2 root root     4096 Aug 10  2022 ./
drwxr-xr-x 5 root root     4096 Aug 10  2022 ../
-rw-r--r-- 1 root root 13705216 Aug 10  2022 classes.jsa
-rw-r--r-- 1 root root 12476416 Aug 10  2022 classes_nocoops.jsa
-rw-r--r-- 1 root root    12672 Aug 10  2022 libjsig.so
-rw-r--r-- 1 root root 22812600 Aug 10  2022 libjvm.so
```
The permissions are not executable, should i make those executable? Maybe then this bug gets fixed? What java libraries / dependencies need executable permissions? pls help me :)

[libjvm.zip](https://github.com/corretto/corretto-17/files/11478470/libjvm.zip)

**Comment by lutkerd** [comment]
Please don't change permissions on that file, it is the core library of the JVM. If you did change anything I recommend uninstalling and reinstalling Corretto to make sure you are back to the correct and default files and permissions.

Please try to following on Corretto 17.0.7 and let us know if the crashes still occur.
* Run without the ramdrive.
* Test your RAM.
* Run without the Minecraft plugins that have native code.

**Comment by ghost** [comment]
> Please don't change permissions on that file, it is the core library of the JVM. If you did change anything I recommend uninstalling and reinstalling Corretto to make sure you are back to the correct and default files and permissions.
> 
> Please try to following on Corretto 17.0.7 and let us know if the crashes still occur.
> 
> * Run without the ramdrive.
> * Test your RAM.
> * Run without the Minecraft plugins that have native code.

Hello,
I think I found the fix. I installed Java-19 and it works just fine, i guess there was a world called "DripCave" that was causing the crashes, maybe idk. I'm fine right now.

I hope that Minecraft 1.20 will have no crashes. 😁

**Comment by ghost** [comment]
> Please don't change permissions on that file, it is the core library of the JVM. If you did change anything I recommend uninstalling and reinstalling Corretto to make sure you are back to the correct and default files and permissions.
> 
> Please try to following on Corretto 17.0.7 and let us know if the crashes still occur.
> 
> * Run without the ramdrive.
> * Test your RAM.
> * Run without the Minecraft plugins that have native code.

Hello, I think I found the ultimate solution.

I rented a Virtual Server in Germany with 6 Cores and 10 GB RAM and I run there Minecraft, and seems like it doesn't crash at all. My OS is Debian 11 64 bit.

I guess my Homeserver with Ubuntu 20.04 LTS 64 bit is not great, I will move to Debian 11 soon. I hope that Debian 11 is the fix, however its not a "real World example" because, I have only SSH, Wireguard and Minecraft installed. No Docker, Jellyfin, NGINX and so on. But yeah, I guess I will use this Virtual Server for now to play Minecraft :)

**Comment by lutkerd** [comment]
If another machine works well running the same version of Java and all of the same plugins that backs up the assumption it is a local hardware issue.

**Comment by ghost** [comment]
> If another machine works well running the same version of Java and all of the same plugins that backs up the assumption it is a local hardware issue.

Well i have good news, the Minecraft server is running over 3 days now, the 25 hours in htop is not correct ;) Let's see if I'm able to run Minecraft over a week, would be really awesome. Btw, I'm moving tomorrow from **Ubuntu 20.04** to **Debian 11**. I hope I will have no more stupid crashes in the future.

Take a look at my screenshot, as you can see Minecraft is quite Memory Hungry, but I can't run it under 6 GB or else it will be a laggy experience with 32 chunk render distance and over 70 plugins. I will give you guys more information, when I moved to Debian 11. Its so wierd for me, having Minecraft not crashing lol.

![Screenshot 2023-05-30 231422](https://github.com/corretto/corretto-17/assets/132822237/b02fd0fb-8f9b-4903-87fb-c2483ce80528)

**Comment by ghost** [comment]
Can someone please fix this... Every time it crashes, I'm ready to smash the keyboard no joke...
There must be a way to fix those goddamn crashes. I copied the same server to Debian 11 in Germany and It works just fine, now over 8 days with no issues at all. I think its my damn server at home, those RAM sticks have some damage probably, or java is just too stupid too allocate the ram on both RAM Sticks i really don't know.

Maybe its the start command,
 ```screen -L -Logfile mc-1.19.4.log -A -S Minecraft-1.19.4 -d -m "${java_19}" -Xss1024M -Xms42G -Xmx48G -jar "${paper}" --nogui```

Take a look at my crash report and please fix this, I can't stand those crashes anymore really...

Please help me, and let me enjoy Minecraft as it was.

[hs_err_pid100939.log](https://github.com/corretto/corretto-17/files/11664523/hs_err_pid100939.log)

**Comment by ghost** [comment]
Hello, I have very good news :)

I guess I found the issue, it were the RAM Sticks ```G.Skill Trident Z RGB Series 64GB (2 x 32GB) 288-Pin``` those are not working properly on Debian 11, not even on Windows. In Windows 10 it says "2x 16 GB", but in reality it should be 2x 32 GB, but alright.  Now I can finally enjoy Minecraft without having those god-damn crashes. Its kinda "amazing" how a RAM Stick can determine crash or stable system or programs.

Thank you anyone for the help, I really appreciate your efford.
