### ISSUE TITLE
 Only availableProcessors() 1 exposed in version 17.0.4.1

### ISSUE THREAD

**Issue by Myeongseok-Kim** [corretto/corretto-17#131]
hello.
I am running a java service by allocating cpu resources of 1000 millicores or less in EKS.

In the 17.0.4.1 version of corretto-17, java's availableProcessors value only exposes 1. (The number of cpus in the node is 4 cores.)
After changing the version of the base image to corretto-17.0.7, it is exposed as 4 cores as expected.

<img width="714" alt="17 0 4 1" src="https://github.com/corretto/corretto-17/assets/54100684/91ff499b-5b3b-4304-a18d-a3f8e9616341">
<img width="713" alt="17 0 7" src="https://github.com/corretto/corretto-17/assets/54100684/61c5f608-df64-4b1b-aaaf-7f777599b0aa">

**Comment by lutkerd** [comment]
[JDK-8281571](https://bugs.openjdk.org/browse/JDK-8281571) changed in how available CPUs was calculated in 17.0.5. Adding `-XX:+UseContainerCpuShares` will restore the old behavior, but this option will be removed in a future version.
