### ISSUE TITLE
jvm crashed

### ISSUE THREAD

**Issue by ZeyuanGuo** [corretto/corretto-17#138]
### Describe the bug
Unexpected sudden jvm crash

### To Reproduce
Unable to reproduce stably after the crash. When the error is reported, i'm writing an error-info json in an HttpResponse object in an token filter, but the error message is about the C code of opencv, guessing it may be an accidental event.
and the code repo is  [javaLab](https://github.com/112292454/javaOO) (now is private, because it is part of my semester assignments, it is inconvenient to make it public before grading, and it will be public in 2023.July——if any other need it)

### Expected behavior
normal response to http request

### Screenshots
![T $RW9LGVWX}G4$ 8GB$OW7](https://github.com/corretto/corretto-17/assets/92578848/63992a09-3c08-4dac-b835-3cf663d2fe06)
![54LJP B$3`A7VLNZ5 R`P](https://github.com/corretto/corretto-17/assets/92578848/e751b948-bac7-46f6-b5aa-0464cb3bdc70)
（i'm sorry.I just took this situation as "wow I met a jvm crash" to tell my friends before ,and re-run the program in idea fastly, so I haven't left detailed information. It is only issued here because of the prompt text of the screenshot here）

### Platform information
Amazon Corretto version 17.0.5
windows 10  19045.3086

### Additional context
just report that, but not need to solve that, thanks.

For VM crashes, please attach the error report file. By default the file name is `hs_err_pidpid.log`, where pid is the process ID of the process.
here: [hs_err_pid56196.log](https://github.com/corretto/corretto-17/files/11860562/hs_err_pid56196.log)

**Comment by lutkerd** [comment]
This doesn't seem like a JDK issue but a problem in the OpenCV dll or how it's being called based on the call stacks below. There maybe a bug in your code or org.bytedeco.opencv.opencv_face.FaceRecognizer.train where it is passing some bad parameters.

```
Stack: [0x00000098c3800000,0x00000098c3900000],  sp=0x00000098c38fe2b0,  free space=1016k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  [opencv_core460.dll+0x3700b9]

Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
j  org.bytedeco.opencv.opencv_face.FaceRecognizer.train(Lorg/bytedeco/opencv/opencv_core/MatVector;Lorg/bytedeco/opencv/opencv_core/Mat;)V+0
j  com.gzy.javaoolab.utils.FaceModelInstance.train()V+225
j  com.gzy.javaoolab.utils.FaceModelInstance.init()V+8
j  com.gzy.javaoolab.JavaOoLabApplication.main([Ljava/lang/String;)V+10
v  ~StubRoutines::call_stub
```
