### ISSUE TITLE
C  [libio_grpc_netty_shaded_netty_tcnative_linux_x86_641937698999423161887.so+0x29193]  netty_internal_tcnative_SSLContext_JNI_OnLoad+0x7b3

### ISSUE THREAD

**Issue by luyou7** [corretto/corretto-17#139]
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00000000000207d6, pid=1, tid=9
#
# JRE version: OpenJDK Runtime Environment Corretto-17.0.7.7.1 (17.0.7+7) (build 17.0.7+7-LTS)
# Java VM: OpenJDK 64-Bit Server VM Corretto-17.0.7.7.1 (17.0.7+7-LTS, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, linux-amd64)
# Problematic frame:
# C  [libio_grpc_netty_shaded_netty_tcnative_linux_x86_641937698999423161887.so+0x29193]  netty_internal_tcnative_SSLContext_JNI_OnLoad+0x7b3
#
# Core dump will be written. Default location: /core.%e.1.%t

**Comment by lutkerd** [comment]
Can you provide the full hs_err log files for this crash? Is this on AlpineLinux? If so, I don't think the native Netty libraries work on Alpine as the libc implementation is different.

**Comment by olivergillespie** [comment]
Closing because there has been no response, feel free to reopen if you get more info.
