### ISSUE TITLE
fontconfig package missing

### ISSUE THREAD

**Issue by eht-ld** [corretto/corretto-17#159]
Hey folks,

we trying to run Apache FOP on Lambda. To get it working with SVGs we need the fontconfig package. In this old issue [here](https://github.com/corretto/corretto-11/issues/118) you said that this package got shipped with corretto 8 & 11. 
How about corretto 17 ? We cant get this to work...

Thank you!

**Comment by lutkerd** [comment]
Thanks for reporting the issue. I've reached out to the Lambda team that owns the runtime image about this problem.

**Comment by smirnoal** [comment]
I can see `fontconfig` package is available in Java17 Lambda runtime:
```
% docker run -it --rm --entrypoint bash public.ecr.aws/lambda/java:17 
bash-4.2# rpm -q fontconfig
fontconfig-2.13.0-4.3.amzn2.x86_64
```

Could you share the error you are facing?

**Comment by eht-ld** [comment]
Sorry, we found out that this is not a problem with Lambda. The fontconfig package is indeed available. It was a problem with the maven-shade-plugin we were using to create an uber jar. It was mixing up some resource files so that some packages would not load. We solved this by using the ServicesResourceTransformer like this:

```
<configuration>
      <transformers>
          <transformer
                  implementation="org.apache.maven.plugins.shade.resource.ServicesResourceTransformer" />
          <transformer implementation="org.apache.maven.plugins.shade.resource.ManifestResourceTransformer">
              <mainClass> (( insert class name )) </mainClass>
          </transformer>
      </transformers>
</configuration>
```

So you might close this issue. Thank you for the prompt reply.
