### ISSUE TITLE
Fatal Error with G1

### ISSUE THREAD

**Issue by sigJoe** [corretto/corretto-17#184]
### Describe the bug
Recently upgraded a web application from Java 8 to Java 17 deployed via AWS Beanstalk, and we're now intermittently seeing JVM crashes due with the error shown below. This has occurred 14 times between March 27 and April 2, which represents <5% of the instances.

```
# A fatal error has been detected by the Java Runtime Environment:
#
#  Internal Error (g1VMOperations.cpp:118), pid=232604, tid=249671
#  guarantee(target_pause_time_ms > 0.0) failed: target_pause_time_ms = 0.000000 should be positive
#
# JRE version: OpenJDK Runtime Environment Corretto-17.0.10.8.1 (17.0.10+8) (build 17.0.10+8-LTS)
# Java VM: OpenJDK 64-Bit Server VM Corretto-17.0.10.8.1 (17.0.10+8-LTS, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, linux-aarch64)
# Problematic frame:
# V  [libjvm.so+0x750598]  VM_G1CollectForAllocation::VM_G1CollectForAllocation(unsigned long, unsigned int, GCCause::Cause, double)+0x6c
#
# Core dump will be written. Default location: Core dumps may be processed with "/usr/lib/systemd/systemd-coredump %P %u %g %s %t %c %h" (or dumping to /usr/share/tomcat9/core.232604)
#
# JFR recording file will be written. Location: /usr/share/tomcat9/hs_err_pid232604.jfr
#
# An error report file with more information is saved as:
# /usr/share/tomcat9/hs_err_pid232604.log
```

### To Reproduce
Unable to reproduce on demand. 

### Expected behavior
No fatal error

### Platform information
    OS: Amazon Linux 2023
    Version Corretto-17.0.10.8.1 
    AWS Beanstalk Solution Stack: Tomcat 9 with Corretto 17 running on 64bit Amazon Linux 2023/5.1.5

### Additional context

**Comment by sigJoe** [comment]
Tentative solution is updating to 17.0.11.9.1, although at a glance I don't see any obvious code changes that might have addressed the issue.

**Comment by rgithubli** [comment]
Hi, thanks for submitting the report. 

Could you try to use the latest Corretto 17.0.11.9.1? If the issue persists, could you upload the hs_err file? Thanks,

**Comment by sigJoe** [comment]
Turns out the problem was environmental and not a bug

**Comment by pengxiaolong** [comment]
Hi @sigJoe, do you mind to share more details of the environmental problem causing the crash?

**Comment by sigJoe** [comment]
When using the [DataDog APM client for Java](https://github.com/DataDog/dd-trace-java) on aarch64 Java 17 instances with the default G1GC garbage collection, instances under high request loads would intermittently crash with the error shown above. This crash affected server instances regardless of age. It did not impact servers running Java 8.

The same Java 17 environment configured to use ParallelGC had a similar issue that only impacted new instances within the first ~6 minutes of starting up that were experiencing a high request load (basic autoscaler scenario). It would manifest as semi-random(?) memory corruption that referenced different sections of code for every crash, but most often had something to do with the class loader. The crash errors would start like this:
```
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x0000ffff9cde7ee8, pid=3242, tid=4295
#
# JRE version: OpenJDK Runtime Environment Corretto-17.0.12.7.1 (17.0.12+7) (build 17.0.12+7-LTS)
# Java VM: OpenJDK 64-Bit Server VM Corretto-17.0.12.7.1 (17.0.12+7-LTS, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, parallel gc, linux-aarch64)
# Problematic frame:
# V  [libjvm.so+0x5e7ee8]  ConstMethod::localvariable_table_start() const+0x8
```

Additionally, sometimes the instance would not crash but would get stuck serving up 5xx responses to every request and print this error:
```
Caused by: java.lang.ClassNotFoundException: Illegal access: this web application instance has been stopped already. Could not load [org.apache.logging.log4j.message.ParameterizedNoReferenceMessageFactory$StatusMessage]. The following stack trace is thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access.
```

DataDog Support has been made aware, and they have suggested the issue is on the Corretto side. I didn't test with any non-Corretto JVMs. I never managed to reliably reproduce the issue on-demand.

**Comment by sigJoe** [comment]
Also just to clarify, my previous comment about `updating to 17.0.11.9.1` being a solution was incorrect.
When I closed the issue and said `the problem was environmental and not a bug`, that was based on a knee-jerk interpretation of DataDog being the problem.

**Comment by olivergillespie** [comment]
We think this was probably caused by bug in the Amazon Linux kernel affecting 5.10 and 6.1, which has been fixed in the latest release of each.

Fixed versions:
* kernel-5.10.236-227.928.amzn2
* kernel-6.1.134-150.224.amzn2023

This issue is much more likely to occur with certain observability tools such as DataDog profiler, due to the nature of how the bug is triggered, sorry for the tricky debugging! Thanks for your report and investigation.
