### ISSUE TITLE
Native library not accessible from other classloaders

### ISSUE THREAD

**Issue by JuliusNmn** [corretto/corretto-17#187]
The implementation of `findNative` does not conform to the JNI specification 5.2, [Library and Version management](https://docs.oracle.com/javase/8/docs/technotes/guides/jni/spec/invocation.html#library_version).

"Once a native library is loaded, it is visible from all class loaders. Therefore two classes in different class loaders may link with the same native method"

The current implementation only searches through libraries loaded with the current classloader:

```
static long findNative(ClassLoader loader, String entryName) {
        if (loader == null) {
            return BootLoader.getNativeLibraries().find(entryName);
        } else {
            return loader.libraries.find(entryName);
        }
    }
```

loader.libraries is only populated when System.load() is called. For any subsequent classloaders, the list is empty.

https://github.com/corretto/corretto-17/blob/b187ff0a4398fd2ad84c0e6e3fddea14efa03cde/src/java.base/share/classes/java/lang/ClassLoader.java#L2444

**Comment by olivergillespie** [comment]
The spec wording is a bit confusing, but it goes on to say:

> Each class loader manages its own set of native libraries. The same JNI native library cannot be loaded into more than one class loader. Doing so causes UnsatisfiedLinkError to be thrown. For example, System.loadLibrary throws an UnsatisfiedLinkError when used to load a native library into two class loaders. The benefits of this approach are:
> - Name space separation based on class loaders is preserved in native libraries. A native library cannot easily mix classes from different class loaders.
> - In addition, native libraries can be unloaded when their corresponding class loaders are garbage collected.

So this is intentional. The native lib is still 'visible' from other ClassLoaders, just not through this path.

**Comment by JuliusNmn** [comment]
I am only calling loadLibrary once. I get UnsatisfiedLinkErrors when calling native functions in classes loaded from other classloaders. My understanding of "visible" is that the functions should be callable from other classloaders as well. I will upload a demo.

**Comment by olivergillespie** [comment]
```
 import java.net.URL;
 import java.net.URLClassLoader;

 public class Class1 {
     public static void main(String[] args) throws Exception {
         ClassLoader classLoader = new URLClassLoader("custom", new URL[] { new URL("file:/tmp/jni-test/") }, null);
         Class<?> c = classLoader.loadClass("Class2");
         System.out.println("Loaded " + c + " in ClassLoader " + c.getClassLoader());
         c.getDeclaredMethod("nativeMethod").invoke(null);
     }
 }
 ```
 
 ```
  public class Class2 {
     static { System.loadLibrary("testlib"); }
     public static native void nativeMethod();
 }
 ```
 
 ```
$ java17 -Djava.library.path=/tmp/jni-test/ Class1.java
Loaded class Class2 in ClassLoader java.net.URLClassLoader@80169cf
Native call.
```

This seems to work for me, calling Class2's native method (loaded in our URL ClassLoader) from Class1 (loaded in a different ClassLoader). Is this not what you mean?

**Comment by JuliusNmn** [comment]
The following code throws an UnsatisfiedLinkError:

```

public class Main {
    public static void main(String[] args) throws Exception {
        System.out.println("Hello world!");

        System.loadLibrary("mylib");
        URLClassLoader cl1 = new URLClassLoader(new URL[]{new URL("file:///tmp/newclasspath/")});
        System.out.println(cl1);

        Class cls1 = demo1.Class1.class;
        System.out.println(cls1.getClassLoader());
        cls1.getMethod("test").invoke(null);

        Class cls2 = cl1.loadClass("demo2.Class2");
        System.out.println(cls2.getClassLoader());
        cls2.getMethod("test").invoke(null);
    }
}
```


```
Hello world!
java.net.URLClassLoader@5acf9800
jdk.internal.loader.ClassLoaders$AppClassLoader@251a69d7
java.net.URLClassLoader@5acf9800
Hello from native 1
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at Main.main(Main.java:18)
Caused by: java.lang.UnsatisfiedLinkError: 'void demo2.Class2.func()'
	at demo2.Class2.func(Native Method)
	at demo2.Class2.test(Class2.java:5)
	... 5 more
```

In your code, are you able to invoke a native function from Class1?

**Comment by olivergillespie** [comment]
Thanks for the snippet.

You are trying to link the same method from two classes, no? That's not possible, as far as I know. What I showed is that you can call another class's `native` method from a class in a different classloader, not that you can link it twice.

My snippet:

Native lib is loaded by ClassLoaderB.
Class1(ClassLoader A) -> Class2(ClassLoaderB).nativeMethod() // good

Your snippet:

Native lib is loaded by ClassLoaderA.
Main(ClassLoader A) -> Class1(ClassLoaderA).nativeMethod() // good 
Main(ClassLoader A) -> Class2(ClassLoaderB).nativeMethod() // bad, not linked
