### ISSUE TITLE
Amazon Linux 2 package missing

### ISSUE THREAD

**Issue by spinneret** [corretto/corretto-17#19]
Will there be an Amazon Linux 2 package for Corretto 17 similar to the one for Corretto 11 (java-11-amazon-corretto-headless.x86_64)?

**Comment by davecurrie** [comment]
Hi. Yes there will, we are working with the Amazon Linux team to have this available shortly.

**Comment by spinneret** [comment]
Awesome!

**Comment by analytically** [comment]
Hi @davecurrie any update?

**Comment by lutkerd** [comment]
Hello, sorry for the delay! The download links are live on https://docs.aws.amazon.com/corretto/latest/corretto-17-ug/downloads-list.html and the packages should be available in the AL2 yum repositories in early/mid December. 

We made some changes to break everything out into more packages, so there is a headless runtime (JRE), headful package adding X11 and ALSA support, a JDK with tools and a JMods package.

**Comment by spinneret** [comment]
It looks like this is done. I installed Corretto 17 on an EC2 instance with no issues. Thanks!

**Comment by austinarbor** [comment]
Is there a planned cadence to keep the yum package in sync with the most recent release? The Corretto 17 packages on Amazon Linux 2 are still installing 17.0.1 for me
