### ISSUE TITLE
 YUM GPG Key Expired: https://yum.corretto.aws/corretto.key

### ISSUE THREAD

**Issue by onyiuche** [corretto/corretto-17#207]
Thank you for taking the time to help improve OpenJDK and Corretto.

If your request concerns a security vulnerability then please report it by email to aws-security@amazon.com instead of here. (You can find more information regarding security issues at https://aws.amazon.com/security/vulnerability-reporting/.)

Otherwise, if your issue concerns OpenJDK and is not specific to Corretto we ask that you raise it to the OpenJDK community. Depending on your contributor status for OpenJDK, please use the [JDK bug system](https://bugs.openjdk.java.net/) or the appropriate [mailing list](http://mail.openjdk.java.net/mailman/listinfo) for the given problem area or [update project](http://mail.openjdk.java.net/mailman/listinfo/jdk-updates-dev).

If your issue is specific to Corretto, then you are in the right place. Please proceed with the following.

### Describe the bug
The GPG key used for YUM repositories (https://yum.corretto.aws/corretto.key) appears to be outdated, with an expiration date that has passed (2024-12-03). This is causing signature verification errors when using YUM or DNF on Amazon Linux.
-  `Error: Failed to download metadata for repo 'corretto': repomd.xml GPG signature verification error: Bad GPG signature
Ignoring repositories: corretto`

### To Reproduce
Run a command that interacts with the YUM or DNF repositories, such as:
- `yum check-update`
- `dnf check-upgrade`

### Expected behavior
The YUM or DNF command should run without any issues, and the repository checks should complete without errors about the GPG key.

### Platform information
    OS: [e.g. Amazon Linux 2023]
    Version [e.g. "Corretto-17.0.13.11.1" (output from "java -version")]

### Additional context

For VM crashes, please attach the error report file. By default the file name is `hs_err_pidpid.log`, where pid is the process ID of the process.

**Comment by benty-amzn** [comment]
Thanks for reaching out about this. We'll regenerate the repository with the extended key from #206 and this should be resolved.

**Comment by benty-amzn** [comment]
It seems like this only reproduces with `repo_gpgcheck=1` in `/etc/yum.repos.d/corretto.repo`.  This is not the default behavior in Corretto images. Could you let us know what image you're using and whether that line is configured?

**Comment by onyiuche** [comment]
> It seems like this only reproduces with `repo_gpgcheck=1` in `/etc/yum.repos.d/corretto.repo`. This is not the default behavior in Corretto images. Could you let us know what image you're using and whether that line is configured?

@benty-amzn Thanks for the response. The Corretto repository is configured manually via a Chef recipe, which sets `repo_gpgcheck=1`. Since this isn't the default behavior in Corretto images, should I consider disabling `repo_gpgcheck`, or will there still be a plan to provide an updated key like you mentioned earlier?

**Comment by benty-amzn** [comment]
The prod yum repo should now be updated with an extended expiration date. I've confirmed that the issue no longer reproduces for me in `amazoncorretto:21` after adding `repo_gpgcheck=1` to `/etc/yum.repos.d/corretto.repo`

Please let us know if you encounter any further issues.

**Comment by onyiuche** [comment]
@benty-amzn Thank you! I've confirmed that the issue is now resolved for me in `amazoncorretto:17`. I appreciate the assistance. For anyone else experiencing this, make sure to clear the cache for the new key to take effect.
