### ISSUE TITLE
Upgrade Alpine Docker images of amazoncorretto to Alpine 3.21

### ISSUE THREAD

**Issue by ddzz** [corretto/corretto-17#208]
### Is your feature request related to a problem?
The latest Alpine base image used by Corretto (3.20) is out-of-date as the latest Alpine release is 3.21.

### Describe a solution you would like
Release a new image of 17-alpine using Alpine 3.21.

### Describe alternatives you have considered
N/A

### Additional context
N/A

**Comment by benty-amzn** [comment]
Moved to [corretto-docker/#226](https://github.com/corretto/corretto-docker/issues/226)
