### ISSUE TITLE
JVM Crash with netty_internal_tcnative_SSLContext_JNI_OnLoad.

### ISSUE THREAD

**Issue by GrigorievNick** [corretto/corretto-17#211]
### Describe the bug
```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x0000000000020506, pid=1094, tid=1204
#
# JRE version: OpenJDK Runtime Environment Corretto-17.0.13.11.1 (17.0.13+11) (build 17.0.13+11-LTS)
# Java VM: OpenJDK 64-Bit Server VM Corretto-17.0.13.11.1 (17.0.13+11-LTS, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, linux-amd64)
# Problematic frame:
# C  [libcom_google_cloud_spark_bigquery_repackaged_netty_tcnative_linux_x86_644012126129710237211.so+0x2b814]  netty_internal_tcnative_SSLContext_JNI_OnLoad+0xa24
#
# Core dump will be written. Default location: /builds/datacollaboration/datalanding/af-datalake/core.1094
#
# An error report file with more information is saved as:
# /builds/datacollaboration/datalanding/af-datalake/hs_err_pid1094.log
#
# If you would like to submit a bug report, please visit:
#   https://github.com/corretto/corretto-17/issues/
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
```
### To Reproduce
It's constantly reproduced in my Gitlab test with a local spark to BQ connector.
But I have zero idea how to mock it for everybody.

### Expected behavior
no jVM Halt

### Platform information
I have tun in it Gitlab with docker image -  maven:3.9-amazoncorretto-17-alpine

### Additional context
It was ok on JVM 1.8. Get this issue while migrating to JVm 17 as a prerequisite to migrating to EMR-S.

**Comment by benty-amzn** [comment]
This looks like [spring-cloud-gcp #3296](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/issues/3296). As noted in this [comment](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/issues/3296), you can resolve the issue by upgrading to `spring-cloud-gcp-5.8` or newer.

**Comment by GrigorievNick** [comment]
Hi @benty-amzn , 
I don't have any spring cloud in my dependency; I use Spark with BQ connector.

Dependency it comes from
```
            <groupId>com.google.cloud.spark</groupId>
            <artifactId>spark-bigquery-with-dependencies_2.12</artifactId>
            <version>0.41.0</version>
```

**Comment by benty-amzn** [comment]
I'd suggest opening an issue with that dependency, then. This still appears to be an issue with the packaged version of netty, not a Corretto bug.
