### ISSUE TITLE
Specjbb hangs with ShenandoahGCMode=generational

### ISSUE THREAD

**Issue by dchuyko** [corretto/corretto-17#27]
### Describe the bug
SpecJBB 2015 Composite or Backend in Multi hangs after first 15-20 min of the workload.

### To Reproduce
Example command line:

`java -server -XX:+PrintFlagsFinal -Xnoclassgc -XX:-UseAdaptiveSizePolicy -XX:+AlwaysPreTouch -XX:-UsePerfData -XX:-UseNUMA -XX:-UseNUMAInterleaving -XX:InlineSmallCode=20k -XX:CompileThreshold=1000 -XX:+AvoidUnalignedAccesses -XX:+UseSIMDForMemoryOps -XX:-UseFPUForSpilling -XX:-SegmentedCodeCache -XX:MaxInlineLevel=15 -Xmx81920m -Xms81920m -Xmn1024m -XX:+UnlockExperimentalVMOptions -XX:+UseShenandoahGC -XX:ShenandoahGCMode=generational -Xlog:gc=debug,heap*=debug,phases*=debug,gc+age=debug:Composite.gc.log -Dspecjbb.controller.rtcurve.warmup.step=0.7 -Dspecjbb.forkjoin.workers.Tier1=100 -Dspecjbb.forkjoin.workers.Tier2=1 -Dspecjbb.forkjoin.workers.Tier3=16 -Dspecjbb.customerDriver.threads=64 -Dsecjbb.heartbeat.threshold=900000 -jar specjbb2015.jar -m COMPOSITE`

### Expected behavior
The application continue to work and print logs, then terminates after ~2 hrs.

### Platform information
    OS: Red Hat Enterprise Linux, 8.3 (Ootpa)
    Version:  Corretto-17, generational-shenandoah branch, e5f77a070fce76a9547340128b3fef3e97c6a082

### Additional context
    HW: aarch64, Graviton2 (m6g.metal)
    GCC: 8.3.1 20191121 (Red Hat 8.3.1-5) (GCC)

**Comment by dchuyko** [comment]
file:///home/tp/aws/genshen/stacktrace.txt

**Comment by dchuyko** [comment]
Sample stacktrace
https://gist.github.com/dchuyko/9eb692d6c584407df9b6346bf741265c

**Comment by earthling-amzn** [comment]
Thank you for reporting this. The stack trace shows that it's running a FullGC on a safepoint. If the application isn't making progress, it's probably running these back-to-back. Have you tried increasing the size of the young generation? The addition of the young generation is meant to lower the overall heap requirements for Shenandoah, but it may still require a larger young generation than other collectors. Shenandoah does not stop the application threads (much) while it is collecting so it needs a bit of 'head room' to allow it time to finish the cycle before the application threads consume available memory.

**Comment by dchuyko** [comment]
Yes, it is so but this configuration doesn't hang if Shenandoah mode is not generational. It is confusing but after some hesitation it indeed looks right to remove or increase young gen setting for generational case. Will get back with some results.

**Comment by earthling-amzn** [comment]
Are you able to share an update on the results after increasing the size of the young generation?

**Comment by dchuyko** [comment]
I got a series of crashes, latest experiments on the recent tip. Example hs_err-s:
https://gist.github.com/dchuyko/7084a8ddb0c603c81e935a013592d890
https://gist.github.com/dchuyko/5c76e5a14c978e119fcdfcd78d55b154

**Comment by benty-amzn** [comment]
This issue should be resolved in the latest release. Please reopen if you are still encountering issues.
