### ISSUE TITLE
A few tier1 tests fail with generational mode

### ISSUE THREAD

**Issue by zhengyu123** [corretto/corretto-17#32]
### Describe the bug
`#`
`# A fatal error has been detected by the Java Runtime Environment:`
`#`
`#  Internal Error (/home/zhengyu/ws/corretto-17/src/hotspot/share/gc/shenandoah/shenandoahFreeSet.cpp:214), pid=3918956, tid=3918961`
`#  assert(result != __null) failed: Allocation must succeed: free 5440, actual 5440`
`#`
`# JRE version: OpenJDK Runtime Environment (17.0.1) (fastdebug build 17.0.1-internal+0-adhoc.zhengyu.corretto-17)`
`# Java VM: OpenJDK 64-Bit Server VM (fastdebug 17.0.1-internal+0-adhoc.zhengyu.corretto-17, mixed mode, tiered, compressed oops, compressed c
lass ptrs, shenandoah gc, linux-amd64)`
`# Problematic frame:`
`# V  [libjvm.so+0x17ad2be]  ShenandoahFreeSet::try_allocate_in(ShenandoahHeapRegion*, ShenandoahAllocRequest&, bool&)+0x161e`
`#`

### To Reproduce
`make CONF=linux-x86_64-server-fastdebug run-test TEST=tier1 TEST_VM_OPTS=-XX:+UseShenandoahGC -XX:+UnlockExperimentalVMOptions -XX:ShenandoahGCMode=generational`

### Platform information
    OS: [Ubuntu]
    Version [20.04.3 LTS (Focal Fossa)]

### Additional context
Failed tests:

- gc/shenandoah/mxbeans/TestPauseNotifications.java
- gc/shenandoah/mxbeans/TestChurnNotifications.java
- jdk/javadoc/tool/VerifyLocale
- javadoc/doclet/testNestedClasses/TestNestedClasses
- tools/javac/classfiles/attributes/annotations/RuntimeAnnotationsForTopLevelClassTest

[hs_err_pid3918956.log](https://github.com/corretto/corretto-17/files/7643031/hs_err_pid3918956.log)

**Comment by earthling-amzn** [comment]
Looks like the patch for this was sitting upstream. I've pulled it down now.

This assert was vestigial and isn't valid for plab allocations. Padding them to align on card boundaries sometimes means they will not fit in available memory.
