### ISSUE TITLE
Missing vcruntime140_1.dll in bin directory

### ISSUE THREAD

**Issue by PikeTec** [corretto/corretto-17#38]
### Is your feature request related to a problem?
The open-jdk windows build inlcudes the vcruntime140_1.dll in its bin directory. This dll is needed by open jfx (more precisely the glass.dll). The Amzon corretto windows build does not bundle this dll and made it necessary to get the dll from another source (if I am correct e.g. by installing the right C++ redistributables or getting it from the open jdk).
Its a small but annoying disadvatage of using corretto instead of open jdk.

### Describe a solution you would like
Please bundle vcruntime140_1.dll with the windows build of Amazon Corretto

**Comment by lutkerd** [comment]
Hi,
Sorry to see you are running in to an issue. Corretto 17 doesn't include OpenJFX in it's distribution nor does it directly depend on vcruntime140_1.dll. The distribution of OpenJFX should include vcruntime140_1.dll in it's bin directory.

**Comment by PikeTec** [comment]
Hi,
I do not understand either, why OpenJDK/JavaFX developers decided that the DLL is important enough to [include it directly in OpenJDK](https://bugs.openjdk.java.net/browse/JDK-8242468) when its only JavaFX that [needs the DLL to enable VS 2019 builds](https://bugs.openjdk.java.net/browse/JDK-8242507). Maybe there are some further thoughts that are not mentioned in the issues.
I can try to open an OpenJFX ticket but expect them to argue that they have the DLL available in the OpenJDK.

**Comment by lutkerd** [comment]
If you are using the packages from openjfx.io, it does seem to have the dll in the bin directory. Corretto builds against VS 2017 and not 2019. We do not want to include a dll that we do not directly depend on.

**Comment by PikeTec** [comment]
The SDK includes it and a bunch of other dlls that are normally present in the JDK, too. The jmods version includes much less.
But in the end I am on your side. I wouldn't want to include a dll in my software if it does not depends on it.
So if you do not have anything to add I wish you a nice day and some happy last days of December. This ticket may be closed.
