### ISSUE TITLE
Is there any plan to support Apple Arch M1 for Corretto 17?

### ISSUE THREAD

**Issue by enricostara** [corretto/corretto-17#41]
Hi,

I'm currently using azul-17 native build for M1 and I'd like to test the corretto-17 native version for M1 as well.

On the Intel arch, I can see corretto-17 performing better than azul-17 and I'd like to test if the corretto-17 for M1 will be better than azul-17 (for M1) as well.

Is there any plan to support Apple Arch M1 for Corretto 17? do you have any planned release date?

Best
E

**Comment by benty-amzn** [comment]
Hi,

Corretto 17 already has support for macos m1. You can download m1 binaries as a pkg or tar.gz from our [releases page](https://github.com/corretto/corretto-17/releases/tag/17.0.1.12.1) under `macOS aarch64`.  Please let us know if you have any further questions.

**Comment by philBrown** [comment]
No Alpine support though?
