### ISSUE TITLE
17.0.2 not honoring -XX:+ShowCodeDetailsInExceptionMessages for detailed NPE messages

### ISSUE THREAD

**Issue by JeffAtDeere** [corretto/corretto-17#55]
Thank you for taking the time to help improve OpenJDK and Corretto.

If your request concerns a security vulnerability then please report it by email to aws-security@amazon.com instead of here. (You can find more information regarding security issues at https://aws.amazon.com/security/vulnerability-reporting/.)

Otherwise, if your issue concerns OpenJDK and is not specific to Corretto we ask that you raise it to the OpenJDK community. Depending on your contributor status for OpenJDK, please use the [JDK bug system](https://bugs.openjdk.java.net/) or the appropriate [mailing list](http://mail.openjdk.java.net/mailman/listinfo) for the given problem area or [update project](http://mail.openjdk.java.net/mailman/listinfo/jdk-updates-dev).

If your issue is specific to Corretto, then you are in the right place. Please proceed with the following.

### Describe the bug
I start my application with
> java -XX:+ShowCodeDetailsInExceptionMessages -jar jar.jar

My code has a problem and processing is failing with:
> java.lang.NullPointerException: null

### Expected behavior
per https://openjdk.java.net/jeps/358 I expected to get a helpful hint where my NPE is.

### Platform information
    OS: Amazon Linux 2
    Docker image: amazoncorretto:17.0.2

**Comment by simonis** [comment]
@JeffAtDeere can you please attach a reproducer for the problem. Also, can you confirm that this is a Corretto-only bug or does it also happen with other JDK17 distributions?

**Comment by olivergillespie** [comment]
I can't reproduce, so closing this for now. If you have a reproducer feel free to reopen. By the way, `ShowCodeDetailsInExceptionMessages` has defaulted to true since somewhere in JDK15 - see https://bugs.openjdk.java.net/browse/JDK-8247371.

My test:

Test.java
```
public class Test {
    static String a;
    public static void main(String[] args) {
        a.length();
    }
}
```

```
$ java -version
openjdk version "17.0.2" 2022-01-18 LTS
OpenJDK Runtime Environment Corretto-17.0.2.8.1 (build 17.0.2+8-LTS)
OpenJDK 64-Bit Server VM Corretto-17.0.2.8.1 (build 17.0.2+8-LTS, mixed mode, sharing
```

```
$ java Test.java
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "String.length()" because "Test.a" is null
	at Test.main(Test.java:4)
```

```
$ javac Test.java
$ jar --create --file test.jar --main-class Test Test.class
$ java -XX:+ShowCodeDetailsInExceptionMessages -jar test.jar
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "String.length()" because "Test.a" is null
	at Test.main(Test.java:4)
```

so everything looks as expected.
