### ISSUE TITLE
Put the version number in the download file name.

### ISSUE THREAD

**Issue by sigzero** [corretto/corretto-17#65]
For example JDK 17 just says "17" for example which means I needed to hunt around to find it was "17.0.3.6.1".

So instead of (for macOS): 

https://corretto.aws/downloads/latest/amazon-corretto-17-x64-macos-jdk.pkg

This:

https://corretto.aws/downloads/latest/amazon-corretto-17.0.3.6.1-x64-macos-jdk.pkg

**Comment by lutkerd** [comment]
Hello, sorry for the confusion here. Our "latest" links are supposed to point to the most recent release of 17 and not a specific release. This is just a redirect and the package name when downloaded will contain the full version.

We do provide direct links to the build packages on the releases page: https://github.com/corretto/corretto-17/releases/tag/17.0.3.6.1
