### ISSUE TITLE
If there will be a build of Generational-Shenandoah for windows？

### ISSUE THREAD

**Issue by Cran-May** [corretto/corretto-17#70]
Hi, I'm very interested in generational-Shenandoah and would like to evaluate it on Windows Platform.
I know there are pre-compiled builds on https://builds.shipilev.net/openjdk-shenandoah-jdk/, but JDK19 is too new that I can't run the project easily.
So if there will be a generational-shenandoah corretto-17 build for windows in the future? :D

**Comment by kdnilsen** [comment]
We do not currently support Windows distributions.  We are not aware of any reasons why the code will not build and run on Windows.  Official support for Windows will be announced after we are ready for GA release.
