### ISSUE TITLE
JVM crash when launching MC 1.19 using Generational ShenandoahGC

### ISSUE THREAD

**Issue by QPCrummer** [corretto/corretto-17#86]
### Describe the bug
I have ran into this error twice so far, and I have talked to 2 others that also had this issue. It will randomly happen when wandering around in a server. The entire JVM will shutdown and give this log
[hs_err_pid84585.log](https://github.com/corretto/corretto-17/files/9146152/hs_err_pid84585.log)
: 

### Platform information
    OS: Debian 11
    Version: 
openjdk version "17.0.2" 2022-04-08
OpenJDK Runtime Environment Corretto-17.0.2.8.1 (build 17.0.2+8-Nightly)
OpenJDK 64-Bit Server VM Corretto-17.0.2.8.1 (build 17.0.2+8-Nightly, mixed mode, sharing)

**Comment by youmukonpaku1337** [comment]
can confirm, this happens on 1.18.2 too

**Comment by kdnilsen** [comment]
Thank you for your problem report.  We are working on a new release to be announced and distributed soon.  (Expected within a few weeks.)  We'll test the new release on minecraft before we distribute it.

**Comment by kdnilsen** [comment]
Thank you for your problem report.  We are working on a new release to be announced and distributed soon.  (Expected within a few weeks.)
