### ISSUE TITLE
Information about Corretto 17.0.4

### ISSUE THREAD

**Issue by rccha** [corretto/corretto-17#89]
We identified an issue with systems using Amazon Corretto 17.0.4 (July release). This happens in servers using 17.0.4 and fail within C2 compilation of sun.security.ssl.SSLEngineInputRecord::decodeInputRecord.This issue is tracked upstream JBS - [JDK-8292260](https://bugs.openjdk.org/browse/JDK-8292260). The release updates are in progress and will be communicated once complete.

**Comment by olivergillespie** [comment]
Fixed in latest release, 17.0.4.9.1 - see https://github.com/corretto/corretto-17/blob/release-17.0.4.9.1/CHANGELOG.md
