### ISSUE TITLE
A fatal error has been detected by the Java Runtime Environment

### ISSUE THREAD

**Issue by WeeeeeeeeeeS** [corretto/corretto-17#95]
[hs_err_pid165095.log](https://github.com/corretto/corretto-17/files/9461134/hs_err_pid165095.log)
[replay_pid165095.log](https://github.com/corretto/corretto-17/files/9461135/replay_pid165095.log)

it keeps happening, after a couple of hours of running the program, i tried old jdk 11 lts, and it worked just fine

**Comment by WeeeeeeeeeeS** [comment]
tried it with the latest cornetto 17, it also crashed
[hs_err_pid169425.log](https://github.com/corretto/corretto-17/files/9461384/hs_err_pid169425.log)
[replay_pid169425.log](https://github.com/corretto/corretto-17/files/9461385/replay_pid169425.log)

**Comment by yftsai** [comment]
Thanks for reporting the issue. Is it possible to provide the memory dump or the jar file for further investigation?

**Comment by eastig** [comment]
Hi @WeeeeeeeeeeS,
The crash looks similar to https://bugs.openjdk.org/browse/JDK-8285835 which is in progress.

Do you have a reproducer?
